apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-web-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "simple-web-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "simple-web-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: UUID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-web-app.fullname" . }}
spec:
  selector:
    app: {{ include "simple-web-app.name" . }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
